### ISSUE TITLE
Null Pointer Exception when saving coverage data to existing coverage file

### ISSUE THREAD

**Issue by linusthe3rd** [tntim96/JSCover#110]
Lately I've been getting the following exception when running my test suite after a coverage report has already been created (basically, my second test run):

```
jsCover stderr: 20140103 10:46:19.353,548,SEVERE,"Error saving coverage data",jscover.server.InstrumentingRequestHandler,
java.lang.NullPointerException
    at jscover.report.FileData.addCoverage(FileData.java:379)
    at jscover.report.JSONDataMerger.mergeJSONCoverageMaps(JSONDataMerger.java:375)
    at jscover.report.JSONDataMerger.mergeJSONCoverageStrings(JSONDataMerger.java:364)
    at jscover.report.JSONDataSaver.saveJSONData(JSONDataSaver.java:373)
    at jscover.server.InstrumentingRequestHandler.storeReport(InstrumentingRequestHandler.java:420)
    at jscover.server.InstrumentingRequestHandler.handlePost(InstrumentingRequestHandler.java:391)
    at jscover.server.HttpServer.run(HttpServer.java:433)
```
## Workaround

Delete the directory containing your coverage data and re-run your test suite.

**Comment by felquis** [comment]
I had this issue today, used the workaround

**Comment by tntim96** [comment]
@felquis, are you able to follow the instructions above to provide both JSON files?
