### ISSUE TITLE
Instrumenting .js-files with empty switch statement causes NullPointerException

### ISSUE THREAD

**Issue by lanzelot1989** [tntim96/JSCover#179]
When instrumenting the js-files of our AngularJS website I noticed that this function causes a NullPointerException:

<code>
function(n) {
switch (n.status) {}
return t.reject(n)
}
</code>

I use the following command
<code>
java -jar JSCover-all.jar -fs --local-storage -no-instrument=lib beautified instrumented
</code>

The stack trace looks like this
<code>Exception in thread "main" java.lang.NullPointerException
    at org.mozilla.javascript.ast.SwitchStatement.toSource(SwitchStatement.java:158)
    at org.mozilla.javascript.ast.Block.toSource(Block.java:50)
    at org.mozilla.javascript.ast.FunctionNode.toSource(FunctionNode.java:401)
    at org.mozilla.javascript.ast.AstNode.printList(AstNode.java:454)
    ...
at org.mozilla.javascript.ast.AstNode.toSource(AstNode.java:300)
	at jscover.instrument.SourceProcessor.instrumentSource(SourceProcessor.java:436)
	at jscover.instrument.SourceProcessor.processSourceWithoutHeader(SourceProcessor.java:411)
	at jscover.instrument.SourceProcessor.processSource(SourceProcessor.java:403)
	at jscover.instrument.SourceProcessor.processSourceForFileSystem(SourceProcessor.java:395)
	at jscover.instrument.InstrumenterService.instrumentJSForFileSystem(InstrumenterService.java:381)
	at jscover.filesystem.FileSystemInstrumenter.copyFolder(FileSystemInstrumenter.java:404)
	at jscover.filesystem.FileSystemInstrumenter.copyFolder(FileSystemInstrumenter.java:399)
	at jscover.filesystem.FileSystemInstrumenter.copyFolder(FileSystemInstrumenter.java:390)
	at jscover.filesystem.FileSystemInstrumenter.run(FileSystemInstrumenter.java:371)
	at jscover.Main.runFileSystem(Main.java:479)
	at jscover.Main.runJSCover(Main.java:449)
	at jscover.Main.runMain(Main.java:417)
	at jscover.Main.main(Main.java:406)</code>

It would seem that the empty switch statement causes this problem.

Edit: I used your latest drone.io build.

**Comment by tntim96** [comment]
This looks like a Rhino bug. I should be able to fix JSCover's Rhino fork.

**Comment by tntim96** [comment]
You can try the fix from source, [the latest drone.io build](https://drone.io/github.com/tntim96/JSCover/files)
 or the [maven snapshot](https://oss.sonatype.org/content/repositories/snapshots/com/github/tntim96/JSCover/1.0.17-SNAPSHOT/). For maven you'll need to add sonatypes repository with:
```xml
        <pluginRepository>
            <id>Sonatype repository</id>
            <name>Sonatype's Maven repository</name>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
        </pluginRepository>
```

**Comment by lanzelot1989** [comment]
*Thanks again!*

Working as expected now.
