### ISSUE TITLE
Issue with instrumenting.

### ISSUE THREAD

**Issue by saur5784** [tntim96/JSCover#210]
I have no-instrument for "analytics.js" but even after that I am consistently getting this in logs...

20150829 11:09:17.690,11021,INFO,"Instrumenting /modules/about/AboutCtrl.js",jscover.instrument.InstrumenterService,
20150829 11:09:17.799,11048,INFO,"Instrumenting /modules/common/ntCompile/ntCompile.js",jscover.instrument.InstrumenterService,
20150829 11:09:25.372,10819,SEVERE,"/favicon.ico",jscover.server.ProxyService,
java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:211)
	at jscover.server.ProxyService.handleProxyRequest(ProxyService.java:379)
	at jscover.server.ProxyService.handleProxyGet(ProxyService.java:368)
	at jscover.server.InstrumentingRequestHandler.handleGet(InstrumentingRequestHandler.java:475)
	at jscover.server.HttpServer.run(HttpServer.java:416)

20150829 11:09:40.729,11089,SEVERE,"/analytics.js",jscover.server.ProxyService,
java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:211)
	at jscover.server.ProxyService.handleProxyRequest(ProxyService.java:379)
	at jscover.server.ProxyService.handleProxyGet(ProxyService.java:368)
	at jscover.server.InstrumentingRequestHandler.handleGet(InstrumentingRequestHandler.java:475)
	at jscover.server.HttpServer.run(HttpServer.java:416)

**Comment by tntim96** [comment]
This means that the JSCover proxy cannot connect to the host where {{analytics.js}} is hosted.

If you don't want this file served by JSCover, add the {{analytics.js}} file's host to the browsers proxy bypass list.

**Comment by saur5784** [comment]
Thanks for the response.
Analytics.js file is on same host as the other application files, so that
will not help.

**Comment by tntim96** [comment]
Can you try again with [this JAR](http://jscover.sourceforge.net/JSCover-all.jar) and post the logs again?

**Comment by saur5784** [comment]
Still the same...Funny thing, not sure why logs are getting printed twice...

20150903 13:18:23.192,241,INFO,"Instrumenting
/modules/common/ntCompile/ntCompile.js",jscover.instrument.InstrumenterService,
20150903 13:18:23.339,215,INFO,"Instrumenting
/modules/badgingDashboard/BadgingDashboardCtrl.js",jscover.instrument.InstrumenterService,
20150903 13:18:23.339,215,INFO,"Instrumenting
/modules/badgingDashboard/BadgingDashboardCtrl.js",jscover.instrument.InstrumenterService,
20150903 13:18:23.356,212,INFO,"Instrumenting
/modules/onboardedClients/OnboardedClientsCtrl.js",jscover.instrument.InstrumenterService,
20150903 13:18:23.356,212,INFO,"Instrumenting
/modules/onboardedClients/OnboardedClientsCtrl.js",jscover.instrument.InstrumenterService,
20150903 13:18:46.777,282,SEVERE,"/analytics.js",jscover.server.ProxyService,
java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:211)
	at jscover.server.ProxyService.handleProxyRequest(ProxyService.java:379)
	at jscover.server.ProxyService.handleProxyGet(ProxyService.java:368)
	at jscover.server.InstrumentingRequestHandler.handleGet(InstrumentingRequestHandler.java:475)
	at jscover.server.HttpServer.run(HttpServer.java:416)

20150903 13:19:54.517,289,INFO,"Saving JSON",jscover.report.JSONDataSaver,
20150903 13:19:54.517,289,INFO,"Saving JSON",jscover.report.JSONDataSaver,
20150903 13:20:08.943,335,INFO,"Instrumenting /modules/common/ntAppIcon/ntApp

**Comment by tntim96** [comment]
Are you sure you're using the new JAR? I changed the logs to print more information and I don't see it.

**Comment by saur5784** [comment]
using 21 actually...I am using jenkins and maven to run it on another
machine...I dont see this issue when running locally but only when running
via jenkins slave. Do you have 22-snap up that I can use from maven ?

**Comment by tntim96** [comment]
Try with:
```XML
<repositories>
    <repository>
        <id>sonatype-nexus-snapshots</id>
        <name>Sonatype Nexus Snapshots</name>
        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
    </repository>
</repositories>
```

**Comment by saur5784** [comment]
Here...this is good logs..so I will try adding google-analytics to no proxy.

20150903 16:46:53.982,214,INFO,"Instrumenting
20150903 16:46:54.320,240,INFO,"Instrumenting
/modules/common/ntCompile/ntCompile.js",jscover.instrument.InstrumenterService,

20150903 16:47:22.244,277,SEVERE,"http://www.google-analytics.com/analytics.js",jscover.server.ProxyService,
java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
	at

**Comment by saur5784** [comment]
That seemed to have helped. Thank you so much. One last thing..I am
getting this while running the report. Since its a seperate thread, the
driver quits while other thread is still running the report. Is there a way
I can halt or look for in order to prevent this ?

20150904 10:29:08.409,293,INFO,"Saving
JSON",jscover.report.JSONDataSaver, *<= Have a 5 sec sleep then
driver.quit()*
20150904 10:29:13.705,300,WARNING,"Error processing request string
null",jscover.server.HttpServer,
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:209)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at java.io.PushbackInputStream.read(PushbackInputStream.java:186)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at jscover.server.HttpServer.run(HttpServer.java:384)

20150904 10:29:13.987,1,WARNING,"Stopping JSCover",jscover.server.WebDaemon,
20150904 10:29:13.987,1,WARNING,"Stopping JSCover",jscover.server.WebDaemon,

**Comment by tntim96** [comment]
Reports are triggered by issuing a web request to JSCover, so you just have to wait for the response `Coverage data stored at <file location>`. If it's triggered via the UI, take a look at [the manual](http://tntim96.github.io/JSCover/manual/manual.xml#automatingDomIdsWait).

Is this what you're after?

**Comment by saur5784** [comment]
I am using webdriver like this : ((JavascriptExecutor)
webClient).executeScript("jscoverage_report();");
So, what should I wait for complete report to be generated before I move on
to destroy driver ?
Maybe something similar to what you mentioned in 5.1.1Waiting for
JavaScript

**Comment by tntim96** [comment]
I think that should block until the report is saved. Are you sure it's causing a problem.

**Comment by saur5784** [comment]
well, since that is on a different thread than the main, the main thread
kills the driver while jscover thread is still storing the reports.
Thus getting this error : java.net.SocketException: Connection reset

**Comment by tntim96** [comment]
> the main thread kills the driver

Which thread and how? Can't the main thread wait for the thread executing the `((JavascriptExecutor) webClient).executeScript("jscoverage_report();");` to finish?

**Comment by saur5784** [comment]
Its actually the way our internal tool handles driver lifecycle. Is there a
way, you can change return for jscoverage_report and return done or success
after its done ? I can just look for that string ?

**Comment by tntim96** [comment]
It returns the string `Coverage data stored at <file location>` which you can use, but any string returned means that it's done.
