### ISSUE TITLE
emptry json string error

### ISSUE THREAD

**Issue by ramprasadgk** [tntim96/JSCover#211]
Getting this exception when trying to merge reports, the coverage file has one line data with noel

Sep 08, 2015 7:51:12 AM jscover.report.Main mergeJSON
INFO: Merging JSON from '......./jscoverage.json'
Exception in thread "main" java.lang.RuntimeException: org.mozilla.javascript.json.JsonParser$ParseException: Empty JSON string
        at jscover.report.JSONDataMerger.jsonToMap(JSONDataMerger.java:436)
        at jscover.report.Main.mergeJSON(Main.java:443)
        at jscover.report.Main.mergeReports(Main.java:421)
        at jscover.report.Main.runReport(Main.java:411)
        at jscover.report.Main.runMain(Main.java:394)
        at jscover.report.Main.main(Main.java:366)
Caused by: org.mozilla.javascript.json.JsonParser$ParseException: Empty JSON string
        at org.mozilla.javascript.json.JsonParser.readValue(JsonParser.java:85)
        at org.mozilla.javascript.json.JsonParser.parseValue(JsonParser.java:44)
        at jscover.report.JSONDataMerger.jsonToMap(JSONDataMerger.java:412)

**Comment by tntim96** [comment]
Can you upload the `jscoverage.json` files you're trying to merge?
