### ISSUE TITLE
Error while hitting the website in ws frame

### ISSUE THREAD

**Issue by poojagangurde** [tntim96/JSCover#226]
I get an error and jscover does not seems to get the site that i am trying to access.

java.lang.NullPointerException
	at jscover.util.IoUtils.closeQuietly(IoUtils.java:387)
	at jscover.server.ProxyService.handleProxyRequest(ProxyService.java:393)
	at jscover.server.ProxyService.handleProxyGet(ProxyService.java:368)
	at jscover.server.InstrumentingRequestHandler.handleGet(InstrumentingRequestHandler.java:475)
	at jscover.server.HttpServer.run(HttpServer.java:416)

where am i going wrong. pls help..

**Comment by tntim96** [comment]
It looks like a bug. You could turn on [logging](http://tntim96.github.io/JSCover/manual/manual.xml#advancedLogging) to narrow down the problem, but the proxy is difficult to support.

To be certain of avoiding this, you're best of pre-instrumenting on the file-system, and have your server serve up the instrumented code without needing a proxy.

**Comment by poojagangurde** [comment]
Ok will do that and keep you informed.
Meanwhile will also try the [File Mode.](http://tntim96.github.io/JSCover/manual/manual.xml#fileMode)
