### ISSUE TITLE
Reports merge error: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Double

### ISSUE THREAD

**Issue by mdsina** [tntim96/JSCover#266]
Hello, I've found some issue on merging reports:

JSCover version: 2.0.2

```
Exception in thread "main" java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Double
	at jscover.report.JSONDataMerger.getIntOrNull(JSONDataMerger.java:455)
	at jscover.report.JSONDataMerger.jsonToMap(JSONDataMerger.java:411)
	at jscover.report.Main.mergeJSON(Main.java:443)
	at jscover.report.Main.mergeReports(Main.java:421)
	at jscover.report.Main.runReport(Main.java:411)
	at jscover.report.Main.runMain(Main.java:394)
	at jscover.report.Main.main(Main.java:366)
```

The attached file failed to merge

[coverage_issue.txt](https://github.com/tntim96/JSCover/files/1591119/coverage_issue.txt)

**Comment by tntim96** [comment]
I noticed a `NaN` in the JSON. Any idea how that got there? Is it possible to upload the source for that file?

```JSON
  "/utils/types.js": {
    "lineData": [
      null,
      2,
      null,
      null,
      NaN,
      null,
      1
    ],
    "functionData": [
      2
    ],
    "branchData": {}
  }
```

**Comment by tntim96** [comment]
Please re-open if you have more details so that I can reproduce the issue.
