### ISSUE TITLE
NoSuchFieldException when starting as proxy

### ISSUE THREAD

**Issue by manpreet333** [tntim96/JSCover#270]
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

closure-compiler.jar is available in same directory.
Started simple web server and can see it listening on port 8080.

But when I start proxy server with this command:
java -jar JSCover-2.0.5.jar -ws --proxy --port=3128 --report-dir=/scratch/jettest/results/ --include-unloaded-js --local-storage --save-json-only

Hitting the following exception:
May 17, 2018 1:44:17 AM jscover.Main runMain
INFO: Args: -ws,--proxy,--port=3128,--report-dir=/scratch/jettest/results/,--include-unloaded-js,--local-storage,--save-json-only
Exception in thread "main" java.lang.NoSuchFieldError: ECMASCRIPT8
        at jscover.ConfigurationCommon.<init>(ConfigurationCommon.java:385)
        at jscover.server.ConfigurationForServer.<init>(ConfigurationForServer.java:357)
        at jscover.server.ConfigurationForServer.parse(ConfigurationForServer.java:467)
        at jscover.Main.runJSCover(Main.java:456)
        at jscover.Main.runMain(Main.java:426)
        at jscover.Main.main(Main.java:415)

Please advise.

**Comment by tntim96** [comment]
That's weird. I've had a quick look and can't reproduce, but will try again tomorrow.

**Comment by manpreet333** [comment]
Thanks!
